project:
  type: website
  output-dir: docs
  
website:
  title: "EDAV Fall 2023 Community Contribution"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Welcome!
  #     - projects.qmd
  #   tools:
  #     - icon: twitter
  #       href: https://twitter.com/
  #     - icon: github
  #       href: https://github.com/YOURUSERNAME/YOURREPO
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Welcome!"
        contents:
          - welcome.qmd
      - text: "---"
      - section: "Topic 1"
        contents:
          - project1.qmd
      - text: "---"
      - section: "Topic 2"
        contents:
          - project2.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023"
  back-to-top-navigation: true

format:
  html:
    theme: cerulean
    toc: true

editor: source

