project:
  type: website
  output-dir: docs
  
website:
  title: "MY WEB SITE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/jtr13/edav2023
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: cerulean
    toc: true

editor: source

